CREATE TABLE IF NOT EXISTS play (
    play_id TEXT PRIMARY KEY,
    player_id TEXT,
    player_name TEXT,
    game_id TEXT,
    away_team TEXT,
    home_team TEXT,
    date TEXT,
    time TEXT,
    attendance TEXT,
    venue TEXT,
    duration TEXT,
    game_type TEXT,
    defensive_positions TEXT,
    inning TEXT,
    score TEXT,
    outs TEXT,
    runners_on_base TEXT,
    pitches_seen TEXT,
    count TEXT,
    runs_outs TEXT,
    player_team TEXT,
    pitcher TEXT,
    pa_result TEXT,
    pa_result_code TEXT
)